import { Badge, Flex, Group, Paper, SimpleGrid, Text } from "@mantine/core";
import React from "react";
import {
  ArrowForwardUp,
  ClipboardTypography,
  CurrencyDirham,
  Id,
  Man,
  StatusChange,
} from "tabler-icons-react";
import { CurrencyFormatter } from "../../../../../../../../Utils/CommonFormatters";

const PaymentInvoiceModal = ({ row }) => {
  return (
    <Paper>
      <Flex direction={"column"} align={"left"} w={"100%"}>
        {" "}
        <SimpleGrid cols={2}>
          {row?.invoice_ID && (
            <>
              <Group noWrap>
                <Id />
                <Text color="#0487FF" fw={"md"}>
                  Payment Invoice ID
                </Text>
              </Group>
              <Text>{row?.invoice_ID}</Text>{" "}
            </>
          )}
          {row?.status && (
            <>
              <Group noWrap>
                <StatusChange />
                <Text color="#0487FF" fw={"md"}>
                  Status:
                </Text>
              </Group>
              <Badge
                variant="filled"
                w={"50%"}
                color={
                  row?.status === "Approved"
                    ? "green"
                    : row?.status === "Pending"
                    ? "yellow"
                    : "red"
                }
              >
                {row?.status}
              </Badge>
            </>
          )}
          {row?.quotation?.service_type && (
            <>
              <Group noWrap>
                <ClipboardTypography />
                <Text color="#0487FF" fw={"md"}>
                  Service Type
                </Text>
              </Group>
              <Text>{row?.quotation?.service_type}</Text>{" "}
            </>
          )}
          {row?.quotation?.quotation_ID && (
            <>
              <Group noWrap>
                <Id />
                <Text color="#0487FF" fw={"md"}>
                  Quotation ID
                </Text>
              </Group>
              <Text>{row?.quotation?.quotation_ID}</Text>{" "}
            </>
          )}
          {row?.staff?.name && (
            <>
              <Group noWrap>
                <Man />
                <Text color="#0487FF" fw={"md"}>
                  Generated By
                </Text>
              </Group>
              <Text>{row?.staff?.name}</Text>{" "}
            </>
          )}
          {row?.client?.UID && (
            <>
              <Group noWrap>
                <Man />
                <Text color="#0487FF" fw={"md"}>
                  Client UID
                </Text>
              </Group>
              <Text>{row?.client?.UID}</Text>{" "}
            </>
          )}
          {row?.client?.client_name && (
            <>
              <Group noWrap>
                <Man />
                <Text color="#0487FF" fw={"md"}>
                  Client Name
                </Text>
              </Group>
              <Text>{row?.client?.client_name}</Text>{" "}
            </>
          )}

          {row?.amount_received && (
            <>
              <Group noWrap>
                <CurrencyDirham />
                <Text color="#0487FF" fw={"md"}>
                  Inovice Amount
                </Text>
              </Group>
              <Text>{CurrencyFormatter(row?.amount_received)}</Text>{" "}
            </>
          )}
        </SimpleGrid>
      </Flex>
      {/* <Grid>
        <Grid.Col>
          <Divider my={"xs"} />
          {row?.attachments?.map((item, index) => {
            return (
              <Anchor href={item?.path} target="_blank">
                <Group
                  style={{
                    cursor: "pointer",
                  }}
                >
                  {matches && <CloudUpload color="red" />}
                  <Text size={"lg"} weight="bold" color="red">
                    Client Expense Attachments ({index + 1})
                  </Text>
                </Group>
              </Anchor>
            );
          })}
        </Grid.Col>
      </Grid> */}
    </Paper>
  );
};

export default PaymentInvoiceModal;
