import {
  Anchor,
  Badge,
  Divider,
  Flex,
  Grid,
  Group,
  Paper,
  SimpleGrid,
  Text,
} from "@mantine/core";
import React from "react";
import {
  ClipboardTypography,
  CloudUpload,
  CurrencyDirham,
  Exchange,
  Id,
  Man,
  StatusChange,
} from "tabler-icons-react";
import { CurrencyFormatter } from "../../../../../../../../Utils/CommonFormatters";
import { useMediaQuery } from "@mantine/hooks";

const PaymentReceiptModal = ({ row }) => {
  const matches = useMediaQuery("(max-width: 768px)");
  return (
    <Paper>
      <Flex direction={"column"} align={"left"} w={"100%"}>
        {" "}
        <SimpleGrid cols={2}>
          {row?.client?.client_name && (
            <>
              <Group noWrap>
                <Man />
                <Text color="#0487FF" fw={"md"}>
                  Client ID :
                </Text>
              </Group>
              <Text>{row?.client?.UID}</Text>{" "}
            </>
          )}
          {row?.client?.client_name && (
            <>
              <Group noWrap>
                <Man />
                <Text color="#0487FF" fw={"md"}>
                  Client Name :
                </Text>
              </Group>
              <Text>{row?.client?.client_name}</Text>{" "}
            </>
          )}
          {row?.quotation?.quotation_ID && (
            <>
              <Group noWrap>
                <Id />
                <Text color="#0487FF" fw={"md"}>
                  Quotation ID :
                </Text>
              </Group>
              <Text>{row?.quotation?.quotation_ID}</Text>{" "}
            </>
          )}
          {row?.quotation?.service_type && (
            <>
              <Group noWrap>
                <ClipboardTypography />
                <Text color="#0487FF" fw={"md"}>
                  Service Type :
                </Text>
              </Group>
              <Text>{row?.quotation?.service_type}</Text>{" "}
            </>
          )}
          {row?.staff?.name && (
            <>
              <Group noWrap>
                <Exchange />
                <Text color="#0487FF" fw={"md"}>
                  Generated By :
                </Text>
              </Group>
              <Text>{row?.staff?.name}</Text>{" "}
            </>
          )}
          {row?.amount_received && (
            <>
              <Group noWrap>
                <CurrencyDirham />
                <Text color="#0487FF" fw={"md"}>
                  Invoice Amount:
                </Text>
              </Group>
              <Text>{CurrencyFormatter(row?.amount_received)}</Text>
            </>
          )}
          {row?.status && (
            <>
              <Group noWrap>
                <StatusChange />
                <Text color="#0487FF" fw={"md"}>
                  Status:
                </Text>
              </Group>
              <Badge variant="filled" w={"50%"} color="green">
                {row?.status}
              </Badge>
            </>
          )}
        </SimpleGrid>
      </Flex>
      <Grid>
        <Grid.Col>
          <Divider my={"xs"} />
          {row?.attachments?.map((item, index) => {
            return (
              <Anchor href={item?.path} target="_blank">
                <Group
                  style={{
                    cursor: "pointer",
                  }}
                >
                  {matches && <CloudUpload color="red" />}
                  <Text size={"lg"} weight="bold" color="red">
                    Payment Receipts Attachments ({index + 1})
                  </Text>
                </Group>
              </Anchor>
            );
          })}
        </Grid.Col>
      </Grid>
    </Paper>
  );
};

export default PaymentReceiptModal;
