export const routes = {
  home: "/",
  login: "/login",
  admin: "/admin",
  staff: "/staff",
};
export const adminRoutes = {
  adminDashboard: "/admin/dashboard",
  humanResource: "/admin/humanResource",
  staffView: "/admin/humanResource/staff",
  addStaff: "/admin/humanResource/addStaff",
  leaves: "/admin/humanResource/leaves",
  accounts: "/admin/accounts",
  qutotations: "/admin/accounts/qutotations",
  addQutotations: "/admin/accounts/addQutotations",
  editQutotations: "/admin/accounts/addQutotations/:editId",
  invoices: "/admin/accounts/invoices",
  paymentsInvoice: "/admin/accounts/invoices/payments",
  clientExpenseInvoice: "/admin/accounts/invoices/clientExpenses",
  addClientExpenseInvoice: "/admin/accounts/invoices/addClientExpenses",
  officeExpenseInvoice: "/admin/accounts/invoices/officeExpenses",
  addOfficeExpenseInvoice: "/admin/accounts/invoices/addOfficeExpenses",
  receipts: "/admin/accounts/receipts",
  paymentsReceipts: "/admin/accounts/receipts/payments",
  clientExpenseReceipts: "/admin/accounts/receipts/clientExpenses",
  approvedQuotationsReceipts: "/admin/accounts/receipts/approvedQuotations",
  officeExpenseReceipts: "/admin/accounts/receipts/officeExpenses",
  commissions: "/admin/accounts/commissions",
  addLicenses: "/admin/addLicenses",
  editLicenses: "/admin/addLicenses/:editId",
  viewLicenses: "/admin/viewLicenses",
};
export const staffRoutes = {
  staffDashboard: "/staff/dashboard",
  viewClient: "/staff/viewClient",
  addClient: "/staff/addClient",
  editClient: "/staff/addClient/:editId",
  addQuotation: "/staff/addQuotation",
  editQuotation: "/staff/addQuotation/:editId",
  viewQuotation: "/staff/viewQuotations",
  addPaymentInvoice: "/staff/addPaymentInvoice",
  viewPaymentInvoice: "/staff/viewPaymentInvoice",
  addLeaveRequest: "/staff/addLeaveRequest",
  viewLeaveRequest: "/staff/viewLeaveRequest",
  commissions: "/staff/commissions",
};
