import { Badge } from "@mantine/core";
import { Man } from "tabler-icons-react";
import ActionIcons from "../../../../Components/ActionIcons/ActionIcons";
import ApproveModal from "./Modals/ApproveModal";
import RejectModal from "./Modals/RejectModal";

export const QuotationViewHeader = ({setUpdate,pending}) => {
  return [
    {
      name: "S.No",
      selector: (row, index) => index + 1,
      sortable: true,
      width: "80px",
    },
    {
      name: "Client ID",
      selector: (row) => row.client.UID,
      sortable: true,
      width: "130px",
      wrap: true,
    },
    {
      name: "Client Name",
      selector: (row) => row.client.client_name || 'N/A',
      sortable: true,
      wrap: true,
    },
    {
      name: "Service Type",
      selector: (row) => row.service_type,
      sortable: true,
      wrap: true,
    },
    {
      name: "Quotation",
      selector: (row) => row.quotation_ID,
      sortable: true,
      wrap: true,
    },

    {
      name: "Generated By",
      selector: (row) => row.staff.name,
      sortable: true,
      wrap: true,
    },
    {
      name: "Amount",
      selector: (row) => row.grand_total_numeric,
      sortable: true,
      wrap: true,
    },
    {
      name: "Status",
      selector: (row) => {return<Badge style={{cursor:'default'}} color={row.status=='Approved'?'green':(row.status=='Pending'?'yellow':(row.status=='Rejected'?'red':'blue'))}>{row.status}</Badge>},
      sortable: true,
      wrap: true,
    },
    {
      name: "Actions",
      cell: (row) => {
        return(
          <ActionIcons
              Approve={pending=='Pending'?true:false}  
              Reject={pending=='Pending'?true:false}
              Print={pending=='Pending'?false:true}
              disableApproveReject={pending=='Pending'?false:true}
              ApproveModalTitle={"Approve Quotation"}
              RejectModalTitle={"Reject Quotation"}
              ApproveModalComponent={<ApproveModal Data={row} setUpdate={setUpdate} />}
              RejectModalComponent={<RejectModal Data={row} setUpdate={setUpdate} />}
          ></ActionIcons>
        )
      },
      sortable: true,
    },
  ];
};
