import { ActionIcon, Badge, Tooltip } from "@mantine/core";
import { Man, Printer } from "tabler-icons-react";
import ActionIcons from "../../../../Components/ActionIcons/ActionIcons";
import ApproveModal from "./Modals/ApproveModal";
import RejectModal from "./Modals/RejectModal";
import ViewModal from "./Modals/ViewModal";
import { adminRoutes } from "../../../../routes";
import { MainBlue } from "../../../../Utils/ThemeColors";
import QuotationPrint from "./QuotationPrint";
import { CurrencyFormatter } from "../../../../Utils/CommonFormatters";

export const QuotationViewHeader = ({ setUpdate, pending }) => {
  return [
    {
      name: "S.No",
      selector: (row, index) => index + 1,
      sortable: true,
      width: "80px",
    },
    {
      name: "Client ID",
      selector: (row) => row.client.UID,
      sortable: true,
      width: "130px",
      wrap: true,
    },
    {
      name: "Client Name",
      selector: (row) => row.client.client_name || "N/A",
      sortable: true,
      wrap: true,
    },
    {
      name: "Service Type",
      selector: (row) => row.service_type,
      sortable: true,
      wrap: true,
    },
    {
      name: "Quotation",
      selector: (row) => row.quotation_ID,
      sortable: true,
      wrap: true,
    },

    {
      name: "Generated By",
      selector: (row) => row.staff.name,
      sortable: true,
      wrap: true,
    },
    {
      name: "Amount",
      width: "120px",
      selector: (row) => CurrencyFormatter(row.grand_total_numeric),
      sortable: true,
      wrap: true,
    },
    {
      name: "Status",
      width: "120px",
      center: true,
      selector: (row) => {
        return (
          <Badge
            style={{ cursor: "default" }}
            color={
              row.status == "Approved"
                ? "green"
                : row.status == "Pending"
                ? "yellow"
                : row.status == "Rejected"
                ? "red"
                : "blue"
            }
          >
            {row.status}
          </Badge>
        );
      },
      sortable: true,
      wrap: true,
    },
    {
      name: "Actions",
      center: true,
      cell: (row) => {
        return (
          <>
            <ActionIcons
              Approve={pending == "Pending" ? true : false}
              Reject={pending == "Pending" ? true : false}
              disableApproveReject={pending == "Pending" ? false : true}
              RejectModalTitle={"Reject Quotation"}
              RejectModalComponent={
                <RejectModal Data={row} setUpdate={setUpdate} />
              }
              ApproveModalTitle={"Approve Quotation"}
              ApproveModalComponent={
                <ApproveModal Data={row} setUpdate={setUpdate} />
              }
              ModalTitle={"View Quotation"}
              ViewModalComponent={<ViewModal row={row} />}
              edit={row.status === "Approved" ? false : true}
              editUrl={`${adminRoutes.addQutotations}/${row.id}`}
            />
            {pending === "Approved" && <QuotationPrint rowData={row} />}
          </>
        );
      },
      sortable: true,
    },
  ];
};
